spring.config.import=optional:file:./application-local.properties,optional:file:./.env[.properties]
spring.application.name=smart-campus-auth
server.port=8080
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
app.frontend.url=${FRONTEND_URL}
