spring.config.import=optional:file:.env[.properties]
spring.application.name=smart-campus-auth
server.port=8080
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:smart_campus_db}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_CLIENT_SCOPE:email,profile}
jwt.secret=${JWT_SECRET:}
