package com.smcsystem.smart_campus_system.enums;

public enum NotificationType {
    ACCESS_REQUEST_SUBMITTED,
    BOOKING_SUBMITTED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    TICKET_SUBMITTED,
    TICKET_STATUS_CHANGED,
    TICKET_COMMENT_ADDED,
    ACCESS_APPROVED,
    ACCESS_REJECTED,
    ACCOUNT_ACTIVATED,
    ACCOUNT_DEACTIVATED,
    GENERAL
}
