assessmentDomains:
  - cloud-readiness
  - java-upgrade
analysisCoverage: issue-only
targetRuntime: openjdk21
targetComputeServices:
  - azure-appservice
  - azure-aks
  - azure-container-apps
targetOS:
  - linux
  - windows
enableContainerization: false
